# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 11233547afaba485556d745dba73da8f4f55e2fcb8de0d3c296632e7208bf66bf73f1bc3c7cd93d828ac84701792e114756e021fe2d8cfd18e8d2bcf4c9d7bf9

test:
  secret_key_base: 5a62f6a5a9e9ebcf144334912590b914c66deb70d2c72ff9af70c9c7def0765124c8e8064cdc8b2497006f4c3d60d294f7200422bafc9dfdb563570e41ace9dc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
